export const FETCH_DASHBOARD_INIT = 'FETCH_DASHBOARD_INIT';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARD_FAILURE';
export const FETCH_TYPEOPTIONS_SUCCESS = 'FETCH_TYPEOPTIONS_SUCCESS';
export const FETCH_TABLEOPTIONS_SUCCESS = 'FETCH_TABLEOPTIONS_SUCCESS';
export const DASHBOARD_CHANGED_SUCCESS = 'DASHBOARD_CHANGED_SUCCESS,';
